---
apiVersion: v1
kind: Service
metadata:
  name: bfs-mvp-service
spec:
  type: NodePort
  selector:
    # This should match the app name from deployment section
    app: bfs-mvp
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80
      targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bfs-mvp-deployment
  labels:
    app: bfs-mvp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bfs-mvp
  template:
    metadata:
      labels:
        app: bfs-mvp
    spec:
      containers:
      - name: bfs-mvp
        image: mohamadjamal/bfs-mvp:transaction-service-docker-aws
        ports:
        - containerPort: 80