apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvp-transaction-service
  labels:
    app: mvp-transaction-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mvp-transaction-service
  template:
    metadata:
      labels:
        app: mvp-transaction-service
    spec:
      containers:
      - name: mvp-transaction-service
        image: <image-name-with-url>
        ports:
        - containerPort: 80